### ISSUE TITLE
Notification of incoming call - binaries

### ISSUE THREAD

**Issue by slm85kbh** [ReneNulschDE/Lync-Blink-Bridge#1]
Hi again, thanks for your response, I have pasted the request from the old repo for reference:

Hi, Is it possible for you to upload a compiled binary of the new version?
It would be greatly appreciated, as I don't really have space to setup an entire VS environment for a single application..
(Maybe a donation link, to let me buy you a beverage :) )

/Stefan

**Comment by ReneNulschDE** [comment]
What Lync/Skype for Business Version do you use?

**Comment by slm85kbh** [comment]
It's Skype for business 2016 (16.0.4639.1000)

**Comment by slm85kbh** [comment]
Hi, I'm sorry to poke, but I would still very much like the binaries :)

**Comment by ReneNulschDE** [comment]
Hi,

please take a look here. I couldn't test the build because my Blink device does not work on the skype client pc currently. In case of problems you could also send me a direct mail lyblinkbridge( at )nulsch.de

https://www.dropbox.com/sh/1hn9odpu1nymsdx/AADaMGFzAFRMA1KpoQ2wIl_Pa?dl=0

**Comment by slm85kbh** [comment]
Thanks! It works very well, makes it easier to use Skype now :)

**Comment by ReneNulschDE** [comment]
Thx for the feedback.
